package saganet.mx.com.cgf.DataBase.Catalogo;

/**
 * Created by LuisFernando on 15/05/2017.
 */

public enum TipoPreguntaDO{
    CERRADA_UNICA("CERRADA_UNICA"),
    COMPONENTE_CERRADA_UNICA("C_CERRADA_UNICA"),
    CERRADA_MULTIPLE("CERRADA_MULTIPLE"),
    COMPONENTE_CERRADA_MULTIPLE("C_CERRADA_MULTIPLE"),
    CERRADA_FECHA("CERRADA_FECHA"),
    COMPONENTE_CERRADA_FECHA("C_CERRADA_FECHA"),
    CERRADA_HORA("CERRADA_HORA"),
    COMPONENTE_CERRADA_HORA("C_CERRADA_HORA"),
    CERRADA_NUMERICO_RANGO("CERRADA_NUMERICO_RANGO"),
    CERRADA_TEXTO_RANGO("CERRADA_TEXTO_RANGO"),
    CERRADA_FECHA_RANGO("CERRADA_FECHA_RANGO"),
    CERRADA_HORA_RANGO("CERRADA_HORA_RANGO"),
    ABIERTA_TEXTO("ABIERTA_TEXTO"),
    COMPONENTE_ABIERTA_TEXTO("C_ABIERTA_TEXTO"),
    ABIERTA_PARRAFO("ABIERTA_PARRAFO"),
    COMPONENTE_ABIERTA_PARRAFO("C_ABIERTA_PARRAFO"),
    ABIERTA_NUMERICO("ABIERTA_NUMERICO"),
    COMPONENTE_ABIERTA_NUMERICO("C_ABIERTA_NUMERICO"),
    ABIERTA_NUMERICO_RANGO("ABIERTA_NUMERICO_RANGO"),
    COMPONENTE_ABIERTA_NUMERICO_RANGO("C_ABIERTA_NUMERICO_RANGO"),
    ABIERTA_TELEFONO("ABIERTA_TELEFONO"),
    COMPONENTE_ABIERTA_TELEFONO("C_ABIERTA_TELEFONO"),
    ABIERTA_EMAIL("ABIERTA_EMAIL"),
    COMPONENTE_ABIERTA_EMAIL("C_ABIERTA_EMAIL"),
    ABIERTA_FECHA_RANGO("ABIERTA_FECHA_RANGO"),
    ABIERTA_FECHA("ABIERTA_FECHA"),
    COMPONENTE_ABIERTA_FECHA("C_ABIERTA_FECHA"),
    ABIERTA_HORA("ABIERTA_HORA"),
    COMPONENTE_ABIERTA_HORA("C_ABIERTA_HORA"),
    ABIERTA_HORA_RANGO("ABIERTA_HORA_RANGO"),
    ABIERTA_TEXTO_LISTA("ABIERTA_TEXTO_LISTA"),
    ABIERTA_NUMERICO_LISTA("ABIERTA_NUMERICO_LISTA"),
    ABIERTA_TELEFONO_LISTA("ABIERTA_TELEFONO_LISTA"),
    ABIERTA_EMAIL_LISTA("ABIERTA_EMAIL_LISTA"),
    FACE_STATE("FACE_STATE"),
    COMPONENTE_FACE_STATE("C_FACE_STATE"),
    LIKE_DISLIKE("LIKE_DISLIKE"),
    COMPONENTE_LIKE_DISLIKE("C_LIKE_DISLIKE"),
    ITERABLE("ITERABLE"),
    COMPONENTE("COMPONENTE");

    private final String nombre;

    private TipoPreguntaDO(String nombre) {
        this.nombre = nombre;
    }

    public String getNombre() {
        return nombre;
    }
}
